title: Secrets de Musiciens
copyright: "© Secrets de Musiciens 2018"
author: Maxime
url: "https://www.secretsdemusiciens.com"

medias:
- url: https://twitter.com/accordguitare
  fa_icon: fa-twitter
- url: mailto:maxime@accordersaguitare.com
  fa_icon: fa-envelope-o

theme: classical
font: Raleway
lang: fr

mailchimpTitle: "Pour aller plus loin…"
mailchimpLead: "Si vous souhaitez en savoir plus sur les sujets présentés sur 
ce site, et être informé lors de la publication d'un nouvel article, remplissez 
simplement le formulaire ci-dessous :"
mailchimpUrl: https://accordersaguitare.us15.list-manage.com/subscribe/post
mailchimpU: 88f74bac90be8782706e16cfe
mailchimpId: 1ae0e7aa7a
mailchimpHiddenValue: b_88f74bac90be8782706e16cfe_1ae0e7aa7a
